"""v3 schema

Revision ID: 3cc2f42838db
Revises: 
Create Date: 2026-05-10 23:01:08.824648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import threads_tracker.models  # noqa: F401  -- expose custom types (JSONField, etc.)


# revision identifiers, used by Alembic.
revision: str = '3cc2f42838db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_posts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('threads_post_id', sa.String(length=64), nullable=False),
    sa.Column('author_username', sa.String(length=64), nullable=True),
    sa.Column('author_follower_count', sa.Integer(), nullable=True),
    sa.Column('post_url', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('discovery_source', sa.String(length=64), nullable=True),
    sa.Column('initial_likes', sa.Integer(), nullable=True),
    sa.Column('initial_replies', sa.Integer(), nullable=True),
    sa.Column('initial_reposts', sa.Integer(), nullable=True),
    sa.Column('initial_views', sa.Integer(), nullable=True),
    sa.Column('metadata', threads_tracker.models.JSONField(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('threads_post_id')
    )
    with op.batch_alter_table('candidate_posts', schema=None) as batch_op:
        batch_op.create_index('idx_candidate_author', ['author_username'], unique=False)
        batch_op.create_index('idx_candidate_discovered', ['discovered_at'], unique=False)

    op.create_table('keyword_seeds',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_candidates_yielded', sa.Integer(), nullable=False),
    sa.Column('total_promoted', sa.Integer(), nullable=False),
    sa.Column('total_collected', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword')
    )
    op.create_table('llm_records',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('related_id', sa.BigInteger(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_records', schema=None) as batch_op:
        batch_op.create_index('idx_llm_purpose_related', ['purpose', 'related_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_username', sa.String(length=64), nullable=True),
    sa.Column('settings', threads_tracker.models.JSONField(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_chat_id')
    )
    op.create_table('daily_pushes',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('push_date', sa.Date(), nullable=False),
    sa.Column('candidate_post_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('push_type', sa.String(length=16), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_post_id'], ['candidate_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('push_date', 'candidate_post_id', name='uq_daily_push_date_candidate')
    )
    with op.batch_alter_table('daily_pushes', schema=None) as batch_op:
        batch_op.create_index('idx_daily_push_date', ['push_date'], unique=False)

    op.create_table('feedback',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('candidate_post_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('acted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_post_id'], ['candidate_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index('idx_feedback_candidate', ['candidate_post_id'], unique=False)
        batch_op.create_index('idx_feedback_user_action', ['user_id', 'action'], unique=False)

    op.create_table('scoring_records',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('candidate_post_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('details', threads_tracker.models.JSONField(), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['candidate_post_id'], ['candidate_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scoring_records', schema=None) as batch_op:
        batch_op.create_index('idx_scoring_candidate_stage', ['candidate_post_id', 'stage'], unique=False)

    op.create_table('tracked_posts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('candidate_post_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('polling_tier', sa.String(length=16), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('initial_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_post_id'], ['candidate_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_post_id')
    )
    with op.batch_alter_table('tracked_posts', schema=None) as batch_op:
        batch_op.create_index('idx_tracked_polling', ['polling_tier', 'last_polled_at'], unique=False)
        batch_op.create_index('idx_tracked_user', ['user_id'], unique=False)

    op.create_table('post_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tracked_post_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=True),
    sa.Column('repost_count', sa.Integer(), nullable=True),
    sa.Column('new_replies', threads_tracker.models.JSONField(), nullable=True),
    sa.ForeignKeyConstraint(['tracked_post_id'], ['tracked_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_snapshots', schema=None) as batch_op:
        batch_op.create_index('idx_snapshots_post_time', ['tracked_post_id', 'captured_at'], unique=False)

    op.create_table('qa_sessions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tracked_post_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('context_mode', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_reason', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['tracked_post_id'], ['tracked_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qa_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_qa_user_active', ['user_id', 'ended_at'], unique=False)

    op.create_table('related_posts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tracked_post_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('threads_post_id', sa.String(length=64), nullable=False),
    sa.Column('relation_type', sa.String(length=16), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('is_milestone', sa.Boolean(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tracked_post_id'], ['tracked_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('threads_post_id')
    )
    with op.batch_alter_table('related_posts', schema=None) as batch_op:
        batch_op.create_index('idx_related_post', ['tracked_post_id', 'posted_at'], unique=False)

    op.create_table('qa_messages',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=32), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['qa_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qa_messages', schema=None) as batch_op:
        batch_op.create_index('idx_qa_msg_session', ['session_id', 'sent_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa_messages', schema=None) as batch_op:
        batch_op.drop_index('idx_qa_msg_session')

    op.drop_table('qa_messages')
    with op.batch_alter_table('related_posts', schema=None) as batch_op:
        batch_op.drop_index('idx_related_post')

    op.drop_table('related_posts')
    with op.batch_alter_table('qa_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_qa_user_active')

    op.drop_table('qa_sessions')
    with op.batch_alter_table('post_snapshots', schema=None) as batch_op:
        batch_op.drop_index('idx_snapshots_post_time')

    op.drop_table('post_snapshots')
    with op.batch_alter_table('tracked_posts', schema=None) as batch_op:
        batch_op.drop_index('idx_tracked_user')
        batch_op.drop_index('idx_tracked_polling')

    op.drop_table('tracked_posts')
    with op.batch_alter_table('scoring_records', schema=None) as batch_op:
        batch_op.drop_index('idx_scoring_candidate_stage')

    op.drop_table('scoring_records')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index('idx_feedback_user_action')
        batch_op.drop_index('idx_feedback_candidate')

    op.drop_table('feedback')
    with op.batch_alter_table('daily_pushes', schema=None) as batch_op:
        batch_op.drop_index('idx_daily_push_date')

    op.drop_table('daily_pushes')
    op.drop_table('users')
    with op.batch_alter_table('llm_records', schema=None) as batch_op:
        batch_op.drop_index('idx_llm_purpose_related')

    op.drop_table('llm_records')
    op.drop_table('keyword_seeds')
    with op.batch_alter_table('candidate_posts', schema=None) as batch_op:
        batch_op.drop_index('idx_candidate_discovered')
        batch_op.drop_index('idx_candidate_author')

    op.drop_table('candidate_posts')
    # ### end Alembic commands ###
