"""initial schema

Revision ID: a1efa9e7d751
Revises: 
Create Date: 2026-05-04 16:01:35.144697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import threads_tracker.models  # noqa: F401  -- expose custom types (JSONField, etc.)


# revision identifiers, used by Alembic.
revision: str = 'a1efa9e7d751'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_posts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('threads_post_id', sa.String(length=64), nullable=False),
    sa.Column('author_username', sa.String(length=64), nullable=False),
    sa.Column('post_url', sa.Text(), nullable=False),
    sa.Column('original_content', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('detection_source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('polling_tier', sa.String(length=16), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', threads_tracker.models.JSONField(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('threads_post_id')
    )
    with op.batch_alter_table('tracked_posts', schema=None) as batch_op:
        batch_op.create_index('idx_tracked_polling', ['polling_tier', 'last_polled_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_username', sa.String(length=64), nullable=True),
    sa.Column('settings', threads_tracker.models.JSONField(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_chat_id')
    )
    op.create_table('llm_summaries',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tracked_post_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('summary_type', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tracked_post_id'], ['tracked_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tracked_post_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=True),
    sa.Column('repost_count', sa.Integer(), nullable=True),
    sa.Column('new_replies', threads_tracker.models.JSONField(), nullable=True),
    sa.ForeignKeyConstraint(['tracked_post_id'], ['tracked_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_snapshots', schema=None) as batch_op:
        batch_op.create_index('idx_snapshots_post_time', ['tracked_post_id', 'captured_at'], unique=False)

    op.create_table('related_posts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tracked_post_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('threads_post_id', sa.String(length=64), nullable=False),
    sa.Column('relation_type', sa.String(length=16), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tracked_post_id'], ['tracked_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('threads_post_id')
    )
    with op.batch_alter_table('related_posts', schema=None) as batch_op:
        batch_op.create_index('idx_related_post', ['tracked_post_id', 'posted_at'], unique=False)

    op.create_table('subscriptions',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tracked_post_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('notification_settings', threads_tracker.models.JSONField(), nullable=False),
    sa.ForeignKeyConstraint(['tracked_post_id'], ['tracked_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'tracked_post_id'),
    sa.UniqueConstraint('user_id', 'tracked_post_id', name='uq_user_post')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    with op.batch_alter_table('related_posts', schema=None) as batch_op:
        batch_op.drop_index('idx_related_post')

    op.drop_table('related_posts')
    with op.batch_alter_table('post_snapshots', schema=None) as batch_op:
        batch_op.drop_index('idx_snapshots_post_time')

    op.drop_table('post_snapshots')
    op.drop_table('llm_summaries')
    op.drop_table('users')
    with op.batch_alter_table('tracked_posts', schema=None) as batch_op:
        batch_op.drop_index('idx_tracked_polling')

    op.drop_table('tracked_posts')
    # ### end Alembic commands ###
